// Generated by CoffeeScript 1.6.3
(function() {
  var CalDav, Calendar,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    _this = this;

  Calendar = (function() {
    function Calendar(caldav) {
      var _this = this;
      this.caldav = caldav;
      this.convertDateToIcalTime = __bind(this.convertDateToIcalTime, this);
      this.convertICalTimeToISOTime = __bind(this.convertICalTimeToISOTime, this);
      this.addCalendarEntry = __bind(this.addCalendarEntry, this);
      this.calendar = jQuery('#calendar');
      this.calendar.fullCalendar({
        agenda: 'h:mm{ - h:mm}',
        firstDay: 1,
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'month,agendaWeek,agendaDay'
        }
      });
      this.calendar.fullCalendar('addEventSource', function(viewStartDate, viewEndDate) {
        return _this.caldav.get(_this.addCalendarEntry, _this.convertDateToIcalTime(viewStartDate), _this.convertDateToIcalTime(viewEndDate));
      });
    }

    Calendar.prototype.addCalendarEntry = function(calDavEntry) {
      var end, event;
      if ((calDavEntry != null ? calDavEntry.VEVENT : void 0) != null) {
        if (calDavEntry.VEVENT.DTEND) {
          end = this.convertICalTimeToISOTime(calDavEntry.VEVENT.DTEND);
        }
        event = {
          id: calDavEntry.VEVENT.UID,
          title: calDavEntry.VEVENT.SUMMARY,
          start: this.convertICalTimeToISOTime(calDavEntry.VEVENT.DTSTART),
          end: end
        };
        return this.calendar.fullCalendar('renderEvent', event);
      }
    };

    Calendar.prototype.convertICalTimeToISOTime = function(time) {
      var datetime, day, gmt, matches, _ref;
      matches = time.match(/(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?(\d{2})?(Z?)/i);
      matches.shift();
      day = matches.slice(0, 3).join('-');
      time = matches.slice(3, 6).join(':');
      if (time === '::') {
        time = '';
      }
      gmt = (_ref = matches.slice(6) === [void 0]) != null ? _ref : {
        'Z': matches.slice(6)
      };
      datetime = day;
      if (time) {
        datetime += "T" + time;
      }
      if (gmt) {
        datetime += gmt;
      }
      return datetime.toString();
    };

    Calendar.prototype.convertDateToIcalTime = function(date) {
      return date.toISOString().replace(/-|:|\.\d{3}/gi, '');
    };

    return Calendar;

  })();

  CalDav = (function() {
    function CalDav(url, user, password) {
      this.url = url;
      this.user = user;
      this.password = password;
      this.get = __bind(this.get, this);
    }

    CalDav.prototype.get = function(callback, datestart, dateend) {
      var _this = this;
      return jQuery.ajax({
        url: this.url,
        method: "REPORT",
        data: "<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n<C:calendar-query xmlns:D=\"DAV:\" xmlns:C=\"urn:ietf:params:xml:ns:caldav\">\n    <D:prop>\n        <C:calendar-data>\n            <C:expand start=\"" + datestart + "\" end=\"" + dateend + "\"/>\n        </C:calendar-data>\n        <D:getetag/>\n    </D:prop>\n    <C:filter>\n        <C:comp-filter name=\"VCALENDAR\">\n            <C:comp-filter name=\"VEVENT\">\n                <C:time-range start=\"" + datestart + "\" end=\"" + dateend + "\"/>\n            </C:comp-filter>\n        </C:comp-filter>\n    </C:filter>\n</C:calendar-query>",
        headers: {
          "Depth": "1",
          "Content-Type": "application/xml"
        },
        username: this.user,
        password: this.password,
        dataType: "xml",
        success: function(xmlData) {
          return $(xmlData).find("cal\\:calendar-data, calendar-data").each(function(index, data) {
            return callback(_this.parseCalDav($(data).text()));
          });
        }
      });
    };

    CalDav.prototype.parseCalDav = function(calendarString) {
      var CalDavEntry, entry, isSubElement, label, line, lines, subElementName, value, _i, _len;
      CalDavEntry = {};
      isSubElement = false;
      subElementName = "";
      lines = calendarString.split('\r\n');
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        entry = line.split(':');
        label = entry.shift().split(';')[0];
        value = entry.join(':');
        if (label === 'BEGIN') {
          isSubElement = true;
          subElementName = value;
          CalDavEntry[value] = {};
          continue;
        }
        if (label === 'END') {
          isSubElement = false;
          continue;
        }
        if (isSubElement) {
          CalDavEntry[subElementName][label] = value;
        } else {
          CalDavEntry[label] = value;
        }
      }
      return CalDavEntry;
    };

    return CalDav;

  })();

  jQuery(function() {
    var caldav, calendar;
    caldav = new CalDav("/baikal/cal.php/calendars/Reiner/default/", "User", "Password");
    return calendar = new Calendar(caldav);
  });

  /*
  if Notification.permission is "granted"
    setTimeout ->
      new Notification "title", body: "notification body"
    , 1000
  else if Notification.permission isnt 'denied'
    Notification.requestPermission (status) ->
      if Notification.permission is "granted"
        window.location.reload();
      else
        alert "Notifications are disabled."
  */


}).call(this);

/*
//@ sourceMappingURL=index.map
*/
